# Generated by Django 3.1.1 on 2021-06-04 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_App', '0002_auto_20210530_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='branch',
            field=models.CharField(choices=[('CS', 'computer_science'), ('ME', 'mechanical'), ('EE', 'electrical'), ('ECE', 'electronics_comm'), ('IT', 'information_technology')], default='CS', max_length=10),
        ),
        migrations.CreateModel(
            name='UserMarksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_obt_marks', models.PositiveSmallIntegerField()),
                ('tenth_total_marks', models.PositiveSmallIntegerField()),
                ('twelve_obt_marks', models.PositiveSmallIntegerField()),
                ('twelve_total_marks', models.PositiveSmallIntegerField()),
                ('jee_rank', models.PositiveSmallIntegerField(null=True)),
                ('first_sem_marks', models.PositiveSmallIntegerField(null=True)),
                ('second_sem_marks', models.PositiveSmallIntegerField(null=True)),
                ('third_sem_marks', models.PositiveSmallIntegerField(null=True)),
                ('fourth_sem_marks', models.PositiveSmallIntegerField(null=True)),
                ('fifth_sem_marks', models.PositiveSmallIntegerField(null=True)),
                ('sixth_sem_marks', models.PositiveSmallIntegerField(null=True)),
                ('seventh_sem_marks', models.PositiveSmallIntegerField(null=True)),
                ('aggregates', models.PositiveSmallIntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='TPO_App.userinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=80)),
                ('project', models.CharField(max_length=50)),
                ('training_mode', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=7)),
                ('institute_name', models.CharField(max_length=40)),
                ('institute_address', models.CharField(max_length=100)),
                ('institute_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('training_duration', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_detail', to='TPO_App.userinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_dmc', models.FileField(upload_to='documents/tenth_dmc')),
                ('twelvth_dmc', models.FileField(upload_to='documents/twelvth_dmc')),
                ('first_sem_dmc', models.FileField(upload_to='documents/first_sem')),
                ('second_sem_dmc', models.FileField(upload_to='documents/second_sem')),
                ('third_sem_dmc', models.FileField(upload_to='documents/third_sem')),
                ('fourth_sem_dmc', models.FileField(upload_to='documents/fourth_sem')),
                ('fifth_sem_dmc', models.FileField(upload_to='documents/fifth_sem')),
                ('sixth_sem_dmc', models.FileField(upload_to='documents/sixth_sem')),
                ('seventh_sem', models.FileField(upload_to='documents/seventh_sem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_proof', to='TPO_App.userinfomodel')),
            ],
        ),
    ]
