# Generated by Django 3.1.1 on 2021-06-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_App', '0003_auto_20210604_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='passing_year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
