# Generated by Django 3.1.1 on 2021-06-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_App', '0004_auto_20210604_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='passing_year',
            field=models.PositiveIntegerField(default='2022'),
        ),
    ]
