# Generated by Django 3.1.1 on 2021-06-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_App', '0005_auto_20210604_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='passing_year',
            field=models.PositiveIntegerField(default='2022', null=True),
        ),
    ]
