# Generated by Django 3.1.1 on 2021-06-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_App', '0006_auto_20210604_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='father_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='mother_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='phone_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='pincode',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
