# Generated by Django 3.1.1 on 2021-06-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_App', '0008_auto_20210604_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='roll_no',
            field=models.CharField(max_length=10),
        ),
    ]
