# Generated by Django 3.1.1 on 2021-06-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_App', '0009_auto_20210604_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsmodel',
            old_name='seventh_sem',
            new_name='seventh_sem_dmc',
        ),
    ]
