# Generated by Django 3.1.1 on 2021-06-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_App', '0010_auto_20210605_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermarksmodel',
            name='supplees',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
