# Generated by Django 3.1.1 on 2021-06-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_App', '0012_auto_20210605_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermarksmodel',
            name='tenth_percentage',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermarksmodel',
            name='twelve_percentage',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
