# Generated by Django 3.1.1 on 2021-06-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_App', '0013_auto_20210606_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermarksmodel',
            name='fifth_sem_marks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermarksmodel',
            name='first_sem_marks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermarksmodel',
            name='fourth_sem_marks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermarksmodel',
            name='second_sem_marks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermarksmodel',
            name='seventh_sem_marks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermarksmodel',
            name='sixth_sem_marks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermarksmodel',
            name='third_sem_marks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
