# Generated by Django 3.1.1 on 2021-06-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_App', '0014_auto_20210606_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsmodel',
            name='fifth_sem_dmc',
            field=models.FileField(blank=True, upload_to='documents/fifth_sem'),
        ),
        migrations.AlterField(
            model_name='documentsmodel',
            name='first_sem_dmc',
            field=models.FileField(blank=True, upload_to='documents/first_sem'),
        ),
        migrations.AlterField(
            model_name='documentsmodel',
            name='fourth_sem_dmc',
            field=models.FileField(blank=True, upload_to='documents/fourth_sem'),
        ),
        migrations.AlterField(
            model_name='documentsmodel',
            name='second_sem_dmc',
            field=models.FileField(blank=True, upload_to='documents/second_sem'),
        ),
        migrations.AlterField(
            model_name='documentsmodel',
            name='seventh_sem_dmc',
            field=models.FileField(blank=True, upload_to='documents/seventh_sem'),
        ),
        migrations.AlterField(
            model_name='documentsmodel',
            name='sixth_sem_dmc',
            field=models.FileField(blank=True, upload_to='documents/sixth_sem'),
        ),
        migrations.AlterField(
            model_name='documentsmodel',
            name='third_sem_dmc',
            field=models.FileField(blank=True, upload_to='documents/third_sem'),
        ),
    ]
